### ISSUE TITLE
Syngas Producer caused crash

### ISSUE THREAD

**Issue by Drako60** [bdew-minecraft/generators#112]
Tried to place down the syngas controller and instantly crashed. Can't log back in, but others on the server aren't affected by it.

[23/8/2016 22:33:50 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] WARNING: coremods are present:
[23/8/2016 22:33:50 PM]   llibrary (llibrary-1.5.1-1.10.2.jar)
[23/8/2016 22:33:50 PM]   LoadingHook (Mekanism-1.10.2-9.1.1.290.jar)
[23/8/2016 22:33:50 PM]   EnderCorePlugin (EnderCore-1.10.2-0.4.1.49-beta.jar)
[23/8/2016 22:33:50 PM]   NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
[23/8/2016 22:33:50 PM]   LoadingPlugin (Quark-r1.0-52.jar)
[23/8/2016 22:33:50 PM]   FMLPlugin (InventoryTweaks-1.61-58.jar)
[23/8/2016 22:33:50 PM]   LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
[23/8/2016 22:33:50 PM]   CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
[23/8/2016 22:33:50 PM]   LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
[23/8/2016 22:33:50 PM]   MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
[23/8/2016 22:33:50 PM] Contact their authors BEFORE contacting forge
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] // Uh... Did I do that?
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] Time: 8/23/16 10:33 PM
[23/8/2016 22:33:50 PM] Description: Unexpected error
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] java.lang.NoSuchMethodError: net.bdew.lib.data.DataSlotTankRestricted.<init>(Ljava/lang/String;Lnet/bdew/lib/data/base/DataSlotContainerTicking;ILnet/minecraftforge/fluids/Fluid;)V
[23/8/2016 22:33:50 PM]     at net.bdew.generators.controllers.syngas.TileSyngasController.<init>(TileSyngasController.scala:41)
[23/8/2016 22:33:50 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23/8/2016 22:33:50 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at java.lang.Class.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at net.bdew.lib.block.HasTE$class.createNewTileEntity(HasTE.scala:32)
[23/8/2016 22:33:50 PM]     at net.bdew.lib.multiblock.block.BlockController.func_149915_a(BlockController.scala:26)
[23/8/2016 22:33:50 PM]     at net.minecraft.block.Block.createTileEntity(Block.java:1204)
[23/8/2016 22:33:50 PM]     at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
[23/8/2016 22:33:50 PM]     at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
[23/8/2016 22:33:50 PM]     at net.minecraft.world.World.func_175625_s(World.java:2402)
[23/8/2016 22:33:50 PM]     at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:57)
[23/8/2016 22:33:50 PM]     at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
[23/8/2016 22:33:50 PM]     at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_594_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
[23/8/2016 22:33:50 PM]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
[23/8/2016 22:33:50 PM]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[23/8/2016 22:33:50 PM]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[23/8/2016 22:33:50 PM]     at net.minecraft.client.main.Main.main(SourceFile:124)
[23/8/2016 22:33:50 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23/8/2016 22:33:50 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23/8/2016 22:33:50 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23/8/2016 22:33:50 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
[23/8/2016 22:33:50 PM]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23/8/2016 22:33:50 PM]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[23/8/2016 22:33:50 PM] ---------------------------------------------------------------------------------------
[23/8/2016 22:33:50 PM] 
[23/8/2016 22:33:50 PM] -- Head --
[23/8/2016 22:33:50 PM] Thread: Client thread
[23/8/2016 22:33:50 PM] Stacktrace:
[23/8/2016 22:33:50 PM]     at net.bdew.generators.controllers.syngas.TileSyngasController.<init>(TileSyngasController.scala:41)
[23/8/2016 22:33:50 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23/8/2016 22:33:50 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at java.lang.Class.newInstance(Unknown Source)
[23/8/2016 22:33:50 PM]     at net.bdew.lib.block.HasTE$class.createNewTileEntity(HasTE.scala:32)
[23/8/2016 22:33:50 PM]     at net.bdew.lib.multiblock.block.BlockController.func_149915_a(BlockController.scala:26)
[23/8/2016 22:33:50 PM]     at net.minecraft.block.Block.createTileEntity(Block.java:1204)
[23/8/2016 22:33:50 PM]     at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
[23/8/2016 22:33:50 PM]     at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
[23/8/2016 22:33:50 PM]     at net.minecraft.world.World.func_175625_s(World.java:2402)
[23/8/2016 22:33:50 PM]     at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:57)
[23/8/2016 22:33:50 PM]     at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
[23/8/2016 22:33:50 PM]     at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_594_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[23/8/2016 22:33:50 PM]     at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
[23/8/2016 22:33:50 PM]

**Comment by bdew** [comment]
This is 99% a mismatch between the versions of BDLib and Advanced Generators. Make sure you are using the latest versions of both mods. If that doesn't fix the issue - post the full crash report please.
