### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KeepOnDigging** [bdew-minecraft/generators#12]
I just updated to the latest build of generators and MC crashes on startup:

java.lang.NullPointerException
at net.bdew.generators.compat.BCCompat$.getCombustionEngineFuels(BCCompat.scala:21) ~[BCCompat$.class:?]
at net.bdew.generators.config.TurbineFuel$.init(TurbineFuel.scala:23) ~[TurbineFuel$.class:?]
at net.bdew.generators.Generators$.init(Generators.scala:50) ~[Generators$.class:?]
at net.bdew.generators.Generators.init(Generators.scala) ~[Generators.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.2.1231-universal.jar:?]
...

I do not have Buildcraft installed.

**Comment by bdew** [comment]
Post the full forge log please

**Comment by KeepOnDigging** [comment]
http://www.keepondigging.com/fml-client-2.log.zip

**Comment by bdew** [comment]
Try this version - http://jenkins.bdew.net/job/generators-1.7.10/25/artifact/build/libs/generators-mc1710-0.9.4.25.jar

**Comment by KeepOnDigging** [comment]
That's fixed it! 

Well done :)
