### ISSUE TITLE
Server startup error: java.lang.NoSuchMethodError net.bdew.lib.sensors.SensorSystem.disabledTexture()Lnet/bdew/lib/gui/Texture

### ISSUE THREAD

**Issue by BakermanLP** [bdew-minecraft/generators#29]
I got a error on server startup about textures with the newest jenkins builds:
- ae2stuff-mc1710-0.1.7.16.jar
- bdlib-mc1710-1.7.0.63.jar
- gendustry-mc1710-1.4.9.71.jar
- generators-mc1710-0.9.12.56.jar
- neiaddons-mc1710-1.12.6.18.jar
- pressure-mc1710-1.1.0.82.jar

---- Minecraft Crash Report ----
// Oops.

Time: 24.03.15 11:09
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.bdew.lib.sensors.SensorSystem.disabledTexture()Lnet/bdew/lib/gui/Texture;
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: net.bdew.lib.sensors.SensorSystem.disabledTexture()Lnet/bdew/lib/gui/Texture;
        at net.bdew.lib.sensors.SensorSystem$DisabledSensor$.<init>(SensorSystem.scala:62)
        at net.bdew.lib.sensors.SensorSystem.DisabledSensor$lzycompute(SensorSystem.scala:53)
        at net.bdew.lib.sensors.SensorSystem.DisabledSensor(SensorSystem.scala:53)
        at net.bdew.generators.sensor.Sensors$.<init>(Sensors.scala:25)
        at net.bdew.generators.sensor.Sensors$.<clinit>(Sensors.scala)
        at net.bdew.generators.Generators$.init(Generators.scala:63)
        at net.bdew.generators.Generators.init(Generators.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
        ... 5 more

**Comment by bdew** [comment]
Yay server only crashes. Should be fixed with the new build of bdlib i hope.

Note that i'm not actively testing on dedicated servers for most dev builds, so use at your own risk (but do keep reporting bugs if you find them :P)

**Comment by BakermanLP** [comment]
That's fine for us. The error occured on our development system. And we know, that these builds are dev builds.

**Comment by bdew** [comment]
I'm assuming that this is fixed and closing the issue. If the problem still exists please comment here or open a new issue.

**Comment by BakermanLP** [comment]
Sorry, you are right. It works.

bdew notifications@github.com schrieb am Mi., 25. Mär. 2015 16:58:
