### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#83]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-E-full.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/10/16 1:31 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.bdew.generators.controllers.turbine.TileTurbineController.inputFluid(TileTurbineController.scala:88)
    at net.bdew.generators.modules.fluidInput.TileFluidInput$$anonfun$fill$2.apply(TileFluidInput.scala:23)
    at net.bdew.generators.modules.fluidInput.TileFluidInput$$anonfun$fill$2.apply(TileFluidInput.scala:23)
    at scala.Option.map(Option.scala:145)
    at net.bdew.generators.modules.fluidInput.TileFluidInput.fill(TileFluidInput.scala:23)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1$$anonfun$apply$1.apply$mcVI$sp(FluidInterfacePipe.scala:97)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:93)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:89)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.tryExtractResources(FluidInterfacePipe.scala:89)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.doExtraction(FluidInterfacePipe.scala:81)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:99)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.onServerTick(FluidInterfacePipe.scala:20)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:88)
    at com.dyonovan.neotech.pipes.types.AdvancedPipe.func_73660_a(AdvancedPipe.scala:38)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.bdew.generators.controllers.turbine.TileTurbineController.inputFluid(TileTurbineController.scala:88)
    at net.bdew.generators.modules.fluidInput.TileFluidInput$$anonfun$fill$2.apply(TileFluidInput.scala:23)
    at net.bdew.generators.modules.fluidInput.TileFluidInput$$anonfun$fill$2.apply(TileFluidInput.scala:23)
    at scala.Option.map(Option.scala:145)
    at net.bdew.generators.modules.fluidInput.TileFluidInput.fill(TileFluidInput.scala:23)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1$$anonfun$apply$1.apply$mcVI$sp(FluidInterfacePipe.scala:97)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:93)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:89)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.tryExtractResources(FluidInterfacePipe.scala:89)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.doExtraction(FluidInterfacePipe.scala:81)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:99)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.onServerTick(FluidInterfacePipe.scala:20)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:88)
    at com.dyonovan.neotech.pipes.types.AdvancedPipe.func_73660_a(AdvancedPipe.scala:38)

-- Block entity being ticked --
Details:
    Name: pipeFluidBasicInterface // com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe
    Block type: ID #807 (tile.neotech:pipeFluidBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-265,58,223), Chunk: (at 7,3,15 in -17,13; contains blocks -272,0,208 to -257,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #807 (tile.neotech:pipeFluidBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: Ur-Anus
    All players: 1 total; [EntityPlayerMP['winsrp'/225, l='Ur-Anus', x=-265.31, y=57.00, z=222.42]]
    Chunk stats: ServerChunkCache: 1111 Drop: 0
    Level seed: -227970885
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: -256.00,64.00,252.00 - World: (-256,64,252), Chunk: (at 0,4,12 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1695460 game time, 1358146 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 39570 (now: false), thunder time: 50640 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 345494232 bytes (329 MB) / 2465693696 bytes (2351 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
    FML: MCP 9.19 Powered by Forge 11.15.1.1762 Optifine OptiFine_1.8.9_HD_U_H4_pre 49 mods loaded, 49 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAA   Forge{11.15.1.1762} [Minecraft Forge] (forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAA   darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAA   MovingWorld{MC1.8.9-INDEV-E} [Moving World] (movingworld-MC1.8.9-INDEV-E-full.jar) 
    UCHIJAAAA   ArchimedesShipsPlus{MC1.8.9-INDEV-D} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8.9-INDEV-D.jar) 
    UCHIJAAAA   ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
    UCHIJAAAA   bdlib{1.10.0.29} [BD Lib] (bdlib-1.10.0.29-mc1.8.9.jar) 
    UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAA   BetterFoliage{2.0.3} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.3.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1926-universal.jar) 
    UCHIJAAAA   bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
    UCHIJAAAA   caterpillar{0.0.0} [Caterpillar] (Caterpillar-1.2.189b76.jar) 
    UCHIJAAAA   cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0-mc1.8.9.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   EnderZoo{1.8.9-1.1.3.35} [Ender Zoo] (EnderZoo-1.8.9-1.1.3.35.jar) 
    UCHIJAAAA   mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
    UCHIJAAAA   reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
    UCHIJAAAA   fluxedredstone{1.3.0.31} [FluxedRedstone] (Fluxed Redstone-1.3.0.31.jar) 
    UCHIJAAAA   substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
    UCHIJAAAA   foundry{1.4.0.0} [Foundry] (Foundry-1.8.9-1.4.0.0.jar) 
    UCHIJAAAA   furnus{1.72} [Furnus] (Furnus-1.8.9-1.72.jar) 
    UCHIJAAAA   pressure{1.3.0.21} [Pressure Pipes] (pressure-1.3.0.21-mc1.8.9.jar) 
    UCHIJAAAA   advgenerators{0.9.19.7} [Advanced Generators] (generators-0.9.19.7-mc1.8.9.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-38-b8950ce} [Inventory Tweaks] (InventoryTweaks-1.60-beta-38.jar) 
    UCHIJAAAA   ironbackpacks{1.8-1.0.7} [Iron Backpacks] (IronBackpacks-1.8-1.0.7.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.5.172} [Just Enough Items] (jei_1.8.9-2.28.5.172.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
    UCHIJAAAA   MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar) 
    UCHIJAAAA   MissingRecipies{0.1.0} [MissingRecipies] (Missing Recipes 0.1.jar) 
    UCHIJAAAA   MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
    UCHIJAAAA   neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
    UCHIJAAAA   progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   wuppy29_simplerecipes{1.9.0} [Simple Recipes] (Simple Recipes 1.8.0-1.9.0.jar) 
    UCHIJAAAA   SpiceOfLife{1.3.1} [The Spice of Life] (SpiceOfLife-mc1.8.9-1.3.1.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
    UCHIJAAAA   storagenetwork{1.7.3} [Storage Network] (StorageNetwork-1.8.9-1.7.3.jar) 
    UCHIJAAAA   usefulrecipes{1.1} [UsefulRecipes] (UsefulRecipes-1.1.0(1.8.9).jar) 
    UCHIJAAAA   usefulstones{0.2} [Useful Stones] (UsefulStones_0.2-MCv1.8.9.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
CorePlugin (Fluxed Redstone-1.3.0.31.jar)

BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  invtweaks.forge.asm.ContainerTransformer
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-E-full.jar)

AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    List of loaded APIs: 
        * AppleCoreAPI (2.0.0) from AppleCore-mc1.8.9-1.3.0.jar
        * BetterAchievements|API (0.1.1) from BetterAchievements-1.8.9-0.1.1.jar
        * CoFHAPI (1.8.9R1.2.0B1) from StorageNetwork-1.8.9-1.7.3.jar
        * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        * CoFHAPI|energy (1.8.9R1.2.0B1) from Bookshelf-API-1.8.9-2.3.6.jar
        * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        * foundry.api (1.4.0.0) from Foundry-1.8.9-1.4.0.0.jar
        * JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.5.172.jar
        * pressureAPI (1.3.0.21) from pressure-1.3.0.21-mc1.8.9.jar
        * reborncoreAPI (1.4.3.20) from RebornCore-1.8.9-1.4.3.20-universal.jar
        * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['winsrp'/225, l='Ur-Anus', x=-265.31, y=57.00, z=222.42]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.8.9_HD_U_H4_pre
    Render Distance Chunks: 16
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: KUDA-Shaders v6.1.13 BETA - Ultra.zip
    OpenGlVersion: 4.5.0 NVIDIA 358.91
    OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8
```

**Comment by bdew** [comment]
That's... odd. What kind of fluid are you trying to pipe there and using what kind of pipe?

**Comment by winsrp** [comment]
I made one of your generators that make syngas, and was moving it to a turbine generator using the neotech fluid pipes, it has a fluid outlet on the syngas and a fuild input on the turbine, moving water into the syngas generator had no issues using the same method but the syngas liquid itself.. blew it up.

**Comment by bdew** [comment]
Good news - i fixed the crash.

Bad  news - it's not going to wrok anyway, for the same reasons why power pipes didn't work.

I'll add a similar workaround (clicking with a wrench to force side into output mode) when i have the time. For now you can use some kind of a tank as a buffer, or other pipes.

**Comment by winsrp** [comment]
hmm.... I think there was another mod that had pipes I'll give it a try. Thanks a lot for the quick fix.

**Comment by winsrp** [comment]
a weird note is that I have the same setup, (one pipe supplying water) from your infinite water source to the syngas fluid intake and that works like a charm.

**Comment by bdew** [comment]
Water source is different, it's a simple tank under the hood.

The problem is with multiblocks that use output modules. The system there is more complicated and requires the output module to detect things it can connect to. Since NT pipes don't provide any interfaces - they don't get detected as valid targets - you can see it by the face not getting that colored square on it that shows that it's connected.
